# pull ubuntu 20.04 base image
FROM ubuntu:22.04

# install nodejs
RUN apt update && apt install nodejs -y

# check node version
RUN node -v

# check npm version
RUN npm -v

# remove node & npm
# RUN apt remove nodejs npm -y