name: Docker Build and Push

on:
  push:
    branches:
      - feature/patch-c
  workflow_dispatch:
    inputs:
      publish:
        description: "push to artifactory"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
env:
  show: true
  event_name: ""
  message: "This is a test message"
  JF_REPO: "local-docker"
  JF_URL: "https://rgnadeem.jfrog.io"
  JF_USER: "nadeem.khalid@regions.com"
  PACKAGE_NAME: "bluegreen"
  IMAGE_NAME: "node-base-image"
  IMAGE_TAG: "v2.0.0"


jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: display workflow input
        run: |
          echo "event_name: ${{ github.event_name }}"
          echo "message: ${{ env.message }}"
          echo "publish: ${{ github.event.inputs.publish }}"
          echo "RF_REPO: ${{ env.JF_REPO }}"
          echo "PACKAGE_NAME: ${{ env.PACKAGE_NAME }}"
          echo "IMAGE_NAME: ${{ env.IMAGE_NAME }}"
          echo "IMAGE_TAG: ${{ env.IMAGE_TAG }}"
      
        # build docker image from Dockerfile
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login to Jfrog
        uses: docker/login-action@v2
        with:
          username: ${{ env.JF_USER }}
          password: ${{ secrets.JF_DOCKER_ACCESS_TOKEN }}
          registry: ${{ env.JF_URL }}
        
      - name: build docker image
        run: |
          mkdir -p ./local-docker
          docker build -f ./dockerfiles/Dockerfile.dev -t ${{ env.IMAGE_NAME}} .
          docker images
          docker tag ${{ env.IMAGE_NAME}} rgnadeem.jfrog.io/local-docker/${{ env.IMAGE_NAME}}:${{ env.IMAGE_TAG}}
          docker push rgnadeem.jfrog.io/local-docker/${{ env.IMAGE_NAME}}:${{ env.IMAGE_TAG}}
          
  Podman-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Podman login to Jfrog
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.JF_USER }}
          password: ${{ secrets.JF_DOCKER_ACCESS_TOKEN }}
          registry: ${{ env.JF_URL }}
        
      - name: Podman build & push image
        run: |
          podman build -f ./dockerfiles/Dockerfile.dev -t ${{ env.IMAGE_NAME}} .
          podman images
          podman tag ${{ env.IMAGE_NAME}} rgnadeem.jfrog.io/local-docker/${{ env.IMAGE_NAME}}:v3.0.0
          podman push rgnadeem.jfrog.io/local-docker/${{ env.IMAGE_NAME}}:v3.0.0