name: Docker Build and Push

on:
  push:
    branches:
      - feature/patch-c
  workflow_dispatch:
    inputs:
      publish:
        description: "push to artifactory"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
env:
  show: true
  event_name: ""
  message: "This is a test message"
  JF_REPO: "local-docker"
  JF_URL: "https://rgnadeem.jfrog.io"
  JF_USER: "nadeem.khalid@regions.com"
  PACKAGE_NAME: "bluegreen"
  IMAGE_NAME: "node-base-image"
  IMAGE_TAG: "v1"


jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: display workflow input
        run: |
          echo "event_name: ${{ github.event_name }}"
          echo "message: ${{ env.message }}"
          echo "publish: ${{ github.event.inputs.publish }}"
          echo "RF_REPO: ${{ env.JF_REPO }}"
          echo "PACKAGE_NAME: ${{ env.PACKAGE_NAME }}"
          echo "IMAGE_NAME: ${{ env.IMAGE_NAME }}"
          echo "IMAGE_TAG: ${{ env.IMAGE_TAG }}"
      
        # build docker image from Dockerfile
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: build docker image
        run: |
          docker build -f ./dockerfiles/Dockerfile.dev -t ${{ env.IMAGE_NAME}}:${{ env.IMAGE_TAG }} ./local-docker
          docker images

      - name: login to Jfrog
        uses: docker/login-action@v2
        with:
          username: ${{ env.JF_USER }}
          password: ${{ secrets.JF_DOCKER_ACCESS_TOKEN }}
          registry: ${{ env.JF_URL }}

      # setup JFrog cli
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: "https://rgnadeem.jfrog.io"
          JF_USER: "nadeem.khalid@regions.com"
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
        # with:
        # jfrog-cli-version: 1.46.1

      - name: check jf cli version
        run: |
          jf --version
          jf rt ping

      # push image to jfrog registry using jf rt command
      - name: push image to JFrog
        run: |
          jf rt dp ${{ env.JF_URL }} docker-build 1.0.0
          jf rt dp ${{ env.JF_URL }} ./loacl-docker
        
