name: echo

on:
  workflow_dispatch:
  

env:
  show: "true"
  branch: ${{ github.ref }}

jobs:
  echo:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Echo
        run: echo "Hello, world!"

      - name: bash shell
        shell: bash
        run: |
          if [ "${{ env.show }}" == "true" ]; then
              echo "${{ env.branch }}"
          else
              echo "Goodbye, world!"
          fi

  artifactory:
    needs: echo
    
    runs-on: ubuntu-latest

    

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup jf cli Artifactory
        uses: jfrog/setup-jfrog-cli@v4

      - name: check jf version
        run: jf --version

        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          JF_URL: ${{ secrets.JF_URL }}

          # Basic authentication credentials
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}

      - name: check jf version
        run: |
          jf rt ping
