name: Build and push to Artifactory

on:
  push:
    branches:
      - feature/patch-1
  workflow_dispatch:
      
jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: helm lint
        shell: bash
        run: |
          echo "Linting the code"
          helm lint ./bluegreen

      - name: helm template
        shell: bash
        run: |
          echo "Helm templating the code"
          helm template ./bluegreen
          

      - name: helm package
        id: package
        shell: bash
        run: |
          echo "Helm packaging the code"
          helm package ./bluegreen

          filename=${ ls *.tgz }
          echo "Filename: $filename"

          echo package-file=$filename >> $GITHUB_ENV

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4

      - name: helm push
        shell: bash
        run: |
          echo "Helm pushing the code"
          echo "Package file: $package-file"
          echo "JF_URL: ${{ secrets.JF_URL }}"
          echo "JF_USER: ${{ secrets.JF_USER }}"
          echo "JF_PASSWORD: ${{ secrets.JF_PASSWORD }}"
          jfrog rt u ${{ steps.package.outputs.package-name }} ${{ secrets.JF_URL }}/helm-local --user ${{ secrets.JF_USER }} --password ${{ secrets.JF_PASSWORD }}
