name: Build and push to Artifactory

on:
  push:
    branches:
      - feature/patch-1
  workflow_dispatch:
      
jobs:
  helm-lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: helm lint
        shell: bash
        run: |
          echo "Linting the code"
          helm lint ./bluegreen

      - name: helm template
        shell: bash
        run: |
          echo "Helm templating the code"
          helm template ./bluegreen

  helm-package-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
          

      - name: helm package
        id: package
        shell: bash
        run: |
          echo "Helm packaging the code"
          helm package ./bluegreen

          filename=bluegreen-0.1.0.tgz
          echo "Filename: $filename"

          echo package-name=$filename >> $GITHUB_OUTPUT
          

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: "https://rgnadeem.jfrog.io"
          JF_USER: "nadeem.khalid@regions.com"
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
        # with:
          shell: bash
          run: |
            jfrog rt config --url $JF_URL --user $JF_USER --password $JF_PASSWORD --interactive=false
            jfrog rt c show
            jfrog rt ping
            jfrog rt --version

            echo "building the file"
            touch test.txt
            echo "Setting the JFrog CLI " >> test.txt
            echo cat test.txt

            jfrog rt upload test.txt nk-helm/ 


      - name: helm push
        shell: bash
        run: |
          echo "package-name --> ${{ steps.package.outputs.package-name }}"
          
