name: Build and push to Artifactory

on:
  push:
    branches:
      - feature/patch-1
  workflow_dispatch:
      
jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: buld lint test
        shell: bash
        run: |
          echo "Building the code"
          echo "Linting the code"
          echo "Testing the code"
          helm lint ./bluegreen

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
        
      - run: |
          jf --version
