name: Build and Tag Docker Image

on:
  push:
    branches:
      - feature/patch-1
  workflow_dispatch:
      
jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - name: Check JFrog CLI version
        run: jf --version

      - name: ping
        run: jf rt ping