name: Build and push to Artifactory

on:
  push:
    branches:
      - feature/patch-1
  workflow_dispatch:
      
jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: helm lint
        shell: bash
        run: |
          echo "Linting the code"
          helm lint ./bluegreen

      - name: helm template
        shell: bash
        run: |
          echo "Helm templating the code"
          helm template ./bluegreen
          

      - name: helm package
        id: package
        shell: bash
        run: |
          echo "Helm packaging the code"
          helm package ./bluegreen

          filename=bluegreen-0.1.0.tgz
          echo "Filename: $filename"

          echo package-name=$filename >> $GITHUB_OUTPUT
          echo package-file=$filename >> $GITHUB_OUTPUT_FILE

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4

      - name: helm push
        shell: bash
        run: |
          echo "package-name --> ${{ steps.package.outputs.package-name }}"
          echo "package-file --> ${{ steps.package.outputs.package-file }}"

          echo "Setting the JFrog CLI " > test.txt
          
          echo "Pushing the helm package to Artifactory"
          jfrog rt u test.txt ${{ secrets.JF_URL }}/helm-local --user ${{ secrets.JF_USER }} --password ${{ secrets.JF_PASSWORD }}
