# This is a basic workflow to help you get started with Actions

name: test if

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:
    inputs:
      publish:
        description: 'push to artifactory'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'


env:
  show: true
  event_name: ""
  message: "This is a test message"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-trigger:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Echo
        shell: bash
        run: |
          echo "trigger step"


      
  
  # This workflow contains a single job called "build"
  test-if:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    if: (github.ref == 'refs/heads/feature/main' || github.event_name == 'workflow_dispatch')
    steps:
        - name: bash if
          shell: bash
          run: |
            set -eux

            echo "ref --> ${{ github.ref }}"
            echo "message --> ${{ env.message }}"
            echo "event name --> ${{ github.event_name }}"
            echo "show --> ${{ env.show }}"
